### ISSUE TITLE
Please check the Installation instructions 

### ISSUE THREAD

**Issue by paladyne-io** [juanjoDiaz/json2csv#10]
I think the installation instructions on https://juanjodiaz.github.io/json2csv/#/quick-start are not correct. For Parser it says to install '--save @json2csv/parsers' but the Usage example shows 'import { Parser } from '@json2csv/plainjs';'  Also 'npm install --save @json2csv/parsers' fails for me. However, installing and using import { Parser } from '@json2csv/plainjs' works.(A Minor point but I also read that --save is not necessary since npm 5 was released in 2017, https://stackoverflow.com/questions/19578796/what-is-the-save-option-for-npm-install)

**Comment by juanjoDiaz** [comment]
Indeed!
Thanks for letting me know.
I'll fix it asap!
