### ISSUE TITLE
Error: Function not implemented.

### ISSUE THREAD

**Issue by CropWatchDevelopment** [juanjoDiaz/json2csv#15]
"@json2csv/plainjs": "^6.1.2"

installed with: npm install --save @json2csv/plainjs

Tested with:
`import { Parser } from '@json2csv/plainjs';
try {
  const parser = new Parser();
  const csv = parser.parse(myData);
  console.log(csv);
} catch (err) {
  console.error(err);
}`

Got: Error: Function not implemented.
This seems like a really cool project, I am not sure why I am getting this error though!
If it can be fixed I would love to come back and use it!

**Comment by CropWatchDevelopment** [comment]
Saw the existing issue, sorry

**Comment by juanjoDiaz** [comment]
Hi @CropWatchDevelopment ,

Is this related to the typescript typings?

**Comment by juanjoDiaz** [comment]
Closing since there is no response
