### ISSUE TITLE
no issue. Just a short howto use json2csv to convert a 1 GB json to csv and import to Postgres

### ISSUE THREAD

**Issue by terchris** [juanjoDiaz/json2csv#17]
Thank you for sharing json2csv. It helped me to convert a 1 GB json and import it into postgres.
It took me some time before I learned how to configure the config file properly. I wrote a small howto and a practical example on how to use the cli. 
[my small howto](https://medium.com/@terchris/converting-and-importing-a-1-gb-json-file-into-a-postgres-database-fc6573d2eeba)

**Comment by juanjoDiaz** [comment]
Thanks for sharing!
