### ISSUE TITLE
Error in .ts file while using transforms

### ISSUE THREAD

**Issue by lupeaserban** [juanjoDiaz/json2csv#26]
1. Include the version of json2csv used and the interface that you are using (plainjs, node or whatwg).
   Using "@json2csv/node": "^6.1.3"
2. Include your node version or your browser vendor and version.
   Node 16

I have my transform function like so: 

```js
      function intToString(item) {
        return {
          intVariable: item.intVariable.toString(),
          ...item,
        };
      }
```

then i have my transforms array and parser next:

```js
const Opts = {
     fields: [ {},  {} ],         // i have some selection enabled here that works fine
     transforms: [ intToString() ]
}

const asyncParser = new AsyncParser(opts);
```

The file is .ts and the error says:

```
Expected 1 arguments, but got 0.ts(2554)
index.ts(42, 28): An argument for 'item' was not provided.
(local function) intToString(item: any): any
```

I also tried with a closure to clear the error and adapted my function to this:

```js
function intToString() {
  return (item) => ({
    intVariable: item.intVariable.toString(),
    ...item,
  });
}
```

However the transformation isn't happening.
 
Any help or lead is appreciated.
Thanks.

**Comment by juanjoDiaz** [comment]
Hi,

Sorry for the delay responding.

```js
      function intToString(item) {
        return {
          intVariable: item.intVariable.toString(),
          ...item,
        };
      }
```
will just return the item as it is.
You probably want:

```js
      function intToString(item) {
        return {
          ...item,
          intVariable: item.intVariable.toString(),
        };
      }
```
so the `intVariable` field is set to the string.

Also, you are not passing the transform. You are executing it.
```js
const Opts = {
     fields: [ {},  {} ],         // i have some selection enabled here that works fine
     transforms: [ intToString ]  // without the parentheses
}
```
If you wan to use the parentheses you just need to use the closure.
The reason it didn't show up before is because what I said before about your transform beign wrong 🙂
