### ISSUE TITLE
Source code included in package

### ISSUE THREAD

**Issue by lohart13** [juanjoDiaz/json2csv#41]
I've just noticed that when installing @json2csv/node, the package includes the src folder with the typescript files as well as the compiled javascript code in the dist folder.

Is this intentional?
I notice that the package.json files for the packages in this repo don't have a `files` option specified.

![image](https://github.com/juanjoDiaz/json2csv/assets/50547373/8fbdc6c8-d848-4702-a5c9-b72bd8c881d5)

The version of @json2csv/node I have installed is 7.0.1 and I'm using node v18.16.0.
To replicate, run `npm install @json2csv/node` or `yarn add @json2csv/node` and browse to the `node_modules/@json2csv/node` folder.

**Comment by juanjoDiaz** [comment]
Hi @lohart13 ,

This is intentional indeed.
Together with the compiled version and the typings, this package also use source maps so debugging tools can be use on the typescript.

Do you see any problem having the source in the package?

**Comment by lohart13** [comment]
This is fine.
It just increases the size of the packages thats all.

If this is intentional, I'll close the issue and PR.
