### ISSUE TITLE
How to specify flattened columns with argument "fields"

### ISSUE THREAD

**Issue by tetsu9923** [juanjoDiaz/json2csv#44]
Thank you for providing great JSON to CSV converter.
We are getting trouble with specifying columns that are flattened by `transforms: [flatten({ arrays: true })]`.
Details are shown below.

## Filing an issue

1. Include the version of json2csv used.
7.0.1

2. Include your node version/browser vendor and version.
18.9.1

3. Include the command or code you used.
```
import { Parser } from "@json2csv/plainjs"
import { flatten } from "@json2csv/transforms"

const data = [
  {
    car: "Audi",
    price: 40000,
    color: ["black", "blue"],  # The length of the array is unknown until it is processed.
  },
  {
    car: "BMW",
    price: 35000,
    color: ["red", "blue"],  # The length of the array is unknown until it is processed.
  },
]

const fields: Array<string> = ["car", "color"]

const parser = new Parser({ fields: fields, transforms: [flatten({ arrays: true })] })
const csv = parser.parse(data)
console.log(csv)
```

4. Include a sample dataset that we can test against.
None (Included in the code above)

5. Include your output/error.

Expected output:
```
"car","color.0","color.1"
"Audi","black","blue"
"BMW","red","blue"
```

Current result:
```
"car","color"
"Audi",
"BMW",
```

The length of the array is unknown until it is processed, so we cannot set fields argument like `["car", "color.0", "color.1"]`.
We are looking for the solution.
Thank you.

**Comment by lhp0730** [comment]
May I ask how it was done ？

**Comment by tjvonbr** [comment]
@tetsu9923 were you able to reach a solution?  I'm running into the same issue recently.
