### ISSUE TITLE
Transform from @json2csv/node appears to not support back-pressure

### ISSUE THREAD

**Issue by luke-lacroix-healthy** [juanjoDiaz/json2csv#45]
I was looking at the source code because some options are not documented (ie. the `objectMode` option that can be passed to `StreamParser` through the `Transform` class). I noticed that the `_transform` function, as implemented, does not support back-pressure. This can lead to high memory consumption if a stream further down the pipeline (ie. a Google Cloud Storage upload stream) is slow (ref: https://github.com/juanjoDiaz/json2csv/blob/main/packages/node/src/Transform.ts#L61C38-L61C38).

I also see that this is an issue further down in `StreamParser` whose `write` function also does not support back-pressure (ref: https://github.com/juanjoDiaz/json2csv/blob/main/packages/plainjs/src/StreamParser.ts#L177).

Am I missing something or does this really not support back-pressure? Normally, the `_transform` function would pass the transformed data to the `done` callback - the base `Transform` implementation would then handle the back-pressure. Example:
```
override _transform(chunk : any, encoding: string, done: TransfomCallback)  {
    done(null, JSON.parse(chunk));
}
```

I have data sets with potentially millions of rows being read in and, without back-pressure, I could easily run the process out of memory if the upload to GCS (or even when writing to the local disk!) is slow.

**Comment by juanjoDiaz** [comment]
Hi @luke-lacroix-healthy ,

Thanks for the very complete issue description.
This seems to be the root cause of #38.

`StreamParser` is fully synchronous. As such, it does not support nor need backpressure.
It's different callbacks are called asynchronous. So, whenever the `write` method completes, everything is already processsed.
Tthe user controlles the writing rate.

`Transform`, however, should support backpressure.
Using the `done` callback method to return data is just an alias for calling the `push` method.
Json2csv Transform, calls the `push` method between 0 and N times for each data chunk depending on how many objects where parsed and ready to be emitted.
Considering that everything is done synchronously inside the `_transform` method, I would expect that backpressure is handled automatically by node.
However, it doesn't seem to be the case...

I would need to do some more profiling to figure out what's going on here.

**Comment by juanjoDiaz** [comment]
Reading Node's docs, it says

>  transform._transform() is never called in parallel; streams implement a queue mechanism, and to receive the next chunk, callback must be called, either synchronously or asynchronously.

So, I would say that there is a memory leak somewhere else.

**Comment by luke-lacroix-healthy** [comment]
When `done()` is called within `_transform`, the next chunk from the input side of the pipe can then be passed to `_transform`. Imagine the following pipeline:
```js
pipeline(
   localFileStream, // 1gbps speed, 10GB file
   new json2csv.Transform(),
   slowInternetStream, // 1kbps speed
);
```

The real problem is that that `_transform` does not wait for the data to be written down-stream and it does not know if down-stream is slow. It registers the `StreamParser.onData` callback in the constructor and simply calls `this.push` for every chunk emitted by the `StreamParser`. This can mean that `slowInternetStream` has a queue of several GB of data which is waiting to be sent and that could exhaust the process of all available memory.

**Comment by juanjoDiaz** [comment]
`_transform` is an internal method so I would expect that calling `done` actually just signals that the transform can continue reading but the actual transform has the logic to do back pressure.

I can't find any info in the docs about this...

**Comment by juanjoDiaz** [comment]
Ok.
As I suspected, I don't think that backpressure is the actual problem.

If you run the following script, you will see that backpressure is working just fine:

```js
import { Readable, Writable } from 'stream';
import { Transform } from '@json2csv/node';

let i = 0;
const inputStream = new Readable();
inputStream._read = function () {
  if (i === 0) this.push('[');
  inputStream.push(`{"id":${i++},"carModel":"Audi","price":0,"color":"blue","power":220},`);

  console.debug(`Reading ${i}`);
};

const outputStream = new Writable({
  write(chunk, encoding, callback) {
    console.log(`Writing: ${chunk}`);
    setTimeout(callback, 1000);
  },
});

const transform = new Transform();

inputStream.pipe(transform).pipe(outputStream);
```

The input is read until the buffer is filled.
Then only read after previous data was consumed (written to the output stream).
Adding a low watermark you can see that the Transform read less before starting writing.

So there must be a memory leak elsewhere.

**Comment by luke-lacroix-healthy** [comment]
I did some additional testing. If I specifically set the high water mark on the transform, ala

```ts
const transform = new Transform({}, {}, {highWaterMark: 10})
```

then back-pressure is applied appropriately. Otherwise, the entire contents of the read stream were read in for me even when a high water mark was applied to the input and output streams.

I cannot immediately wrap my head around how this could possibly work because the callback is being called immediately inside `_transform`... I might have to dig into the `push` method of the streams classes to understand that a bit more.

**Comment by juanjoDiaz** [comment]
Great that you got it working.
Please report back if you find anything else 🙂
