### ISSUE TITLE
Empty data results in error: " Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by sharon182** [juanjoDiaz/json2csv#56]
I'm trying to parse empty data (empty json array) using Node Transform, but in the transoformation phase I'm getting a `Cannot convert undefined or null to object` error.

Is there any support of parsing empty data and get a CSV file with just the header columns  ? 

**Details :** 
* json2csv 6.1.3
* Node Transform module
* Node 18

![SCR-20230918-luzs](https://github.com/juanjoDiaz/json2csv/assets/4376219/8d3cd725-57b2-4a57-b60c-4ffc1a7e863f)

**Comment by sharon182** [comment]
Hi, 
I just updated to the latest version and still have the same issue.
Here is a sample code of my stream parser : 

*Few Notes* 
1. `headersMap` is just a map of json fields to a formatted column name
2. `flatRespById(records)` - is just a method that takes a search response and flat the nested objects by some logic and returns an array of objects that need to be parsed to CSV.
The issue is when the `flatRespById` method returns an empty array and then the error attached to this message is being sent.
```
  createCSVStreamParser(): Transform<SearchResponse, CSVRecords[]> {
    const headersMap = this.headersMap;
    const formatHeaders = () => (recordKey: string) => headersMap.get(recordKey) || recordKey;
    const opts: ParserOptions = {
      formatters: {
        header: formatHeaders(),
      },
      transforms: [
        (records: SearchResponse) => {
          return this.utility.flatRespById(records);
        },
        (record: any) => {
          Object.keys(record).forEach((key) => {
            if (record[key] === 'null') {
              record[key] = '';
            }
          });
          return record;
        },
      ],
    };

    const parser = new Transform(opts, {});
    return parser;
  }
```

![SCR-20230921-kgbr](https://github.com/juanjoDiaz/json2csv/assets/4376219/05e9d415-358d-4a1c-9a50-33351027bcef)

**Comment by sharon182** [comment]
@juanjoDiaz Ok, so i managed to solve this issue by removing the header formatter and set the headers formatting in side the `fields` option as follows: 
```
  createCSVStreamParser(): Transform<SearchResponse, CSVRecords[]> {
    const headersMap = this.headersMap;
    const formatHeaders = () => (recordKey: string) => headersMap.get(recordKey) || recordKey;
    const opts: ParserOptions = {
      fields: buildCustomFields(this.headersMap), //buildCustomFields is a custom method that maps object fields to CSV columns 
      transforms: [
        (records: SearchResponse) => {
          return this.utility.flatRespById(records);
        },
        (record: any) => {
          Object.keys(record).forEach((key) => {
            if (record[key] === 'null') {
              record[key] = '';
            }
          });
          return record;
        },
      ],
    };

    const parser = new Transform(opts, {});
    return parser;
  }
```

**Comment by juanjoDiaz** [comment]
Good that you found a workaround.

The issue is happening here:
https://github.com/juanjoDiaz/json2csv/blob/3f075bd158665e4121964e10e03fd2366e0b5e45/packages/plainjs/src/StreamParser.ts#L187-L190
The first element of your array is `null` so the stream parser cannot auto-detect the fields from that first element.
Even though `null` is a valid JSON object, I would argue that null values are wrong values.
