### ISSUE TITLE
Cell to show in excel as a link with default text (HYPERLINK) 

### ISSUE THREAD

**Issue by igu** [juanjoDiaz/json2csv#61]
Pass json data fields with a link using default text (alias) from column:

Example data obj:

`const obj = [{ link: 'google.com' }]`

Example fields:

`const fields = [{ label: 'Receipt', value: 'link' }]`

Example expected after export with Json2Csv:

| Receipt |
|--------|
| [DOWNLOAD RECEIPT](google.com) |

**Comment by juanjoDiaz** [comment]
Hi @igu,

I need more details on what are you trying to achieve.
What data would you expect on the CSV and what are you getting instead?

**Comment by igu** [comment]
> Hi @igu,
> 
> I need more details on what are you trying to achieve. What data would you expect on the CSV and what are you getting instead?

I see this issue [#503](https://github.com/zemirco/json2csv/issues/503#issuecomment-732151629), from 2 years ago, but no solution working, i need an solution similiar.

**Comment by juanjoDiaz** [comment]
Like I said in #503, CSV is a text-based format. It does not have the concept of hyperlinks.
What you want is some excel-specific behaviour unrelated to CSV.

The solution is to use [formatters](https://juanjodiaz.github.io/json2csv/#/advanced-options/formatters).
You want to extend the string formatter so it detects when something looks like a link and converts it to an excel link.
Something like this:

```js
import type Formatter from './Formatter.js';

function isValidHttpUrl(string) {
  try {
    const url = new URL(string);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch (_) {
    return false;  
  }
}

export default function stringFormatterWithExcelUrlSupport(): Formatter<string> {
  if (isValidHttpUrl(string)) {
    return (value) => `"=HYPERLINK(""value"",""value"")"`;
  }

  const quote = '"';
  const escapedQuote = '""';

  return (value) => {
    if (value.includes(quote)) {
      value = value.replace(new RegExp(quote, 'g'), escapedQuote);
    }

    return `${quote}${value}${quote}`;
  };
}
```
