### ISSUE TITLE
No `promise` method for whatwg `AsyncParser.parse`

### ISSUE THREAD

**Issue by tomtastico** [juanjoDiaz/json2csv#65]
I'm using version 7.0.4

Seems `parse` of the whatwg `AsyncParser` doesn't have a `promise` method like in node? It returns a `ReadableStream`

![image](https://github.com/juanjoDiaz/json2csv/assets/690217/40f8bf9e-3d3a-41c5-8f0c-ce16bf975132)

In the github documentation it mentions there should be `promise`, but then code example uses `TransformStream` and no promises:

https://github.com/juanjoDiaz/json2csv/tree/main/packages/whatwg#whatwg-async-parser

![image](https://github.com/juanjoDiaz/json2csv/assets/690217/c671a99a-3f04-454a-a3da-175c6d0295fd)

While in the HTML, it does show the use of promise, but this doesn't work as shown above:

https://juanjodiaz.github.io/json2csv/#/parsers/whatwg-async-parser

![image](https://github.com/juanjoDiaz/json2csv/assets/690217/fe12a451-7e31-4a2e-98be-2363e706298b)

**Comment by juanjoDiaz** [comment]
Hi @tomtastico ,

Thanks for reporting this.

https://github.com/juanjoDiaz/json2csv/tree/main/packages/whatwg#whatwg-async-parser was incorrectly showing a code example for the `StreamTransform` not the `AsyncParser`.

The example in https://juanjodiaz.github.io/json2csv/#/parsers/whatwg-async-parser should work but there was a bug in the typings.

I'll do a release to fix it asap.

In the mean time, you can work around by simply `const csv = await (parser.parse(data) as any).promise()`.

**Comment by juanjoDiaz** [comment]
Fixed in v7.0.5
