### ISSUE TITLE
Download csv file after converting a big json file

### ISSUE THREAD

**Issue by abhimanu-sharma** [juanjoDiaz/json2csv#8]

**Comment by juanjoDiaz** [comment]
Hi @abhimanu-sharma ,

I need some description to know what you want exactly.
For big downloads I reconmend that you do everything using streams: reading the file, converting it and pushing the csv to the response.

**Comment by abhimanu-sharma** [comment]
Hi @juanjoDiaz ,

I am trying below code,

```
import { createReadStream, createWriteStream } from 'fs';
import { Transform } from '@json2csv/node';

const input = createReadStream(inputPath, { encoding: 'utf8' });
const output = createWriteStream(outputPath, { encoding: 'utf8' });
const parser = new Transform();

const processor = input.pipe(parser).pipe(output);

// You can also listen for events on the conversion and see how the header or the lines are coming out.
json2csv
  .on('header', (header) => console.log(header))
  .on('line', (line) => console.log(line));
```

1. What is json2csv in above code?
2. I have tried res.send(processor) to return the file.
3. I checked outputPath there is no csv file saved on that path.
4. Is there a codesandbox or any working demo?

**Comment by juanjoDiaz** [comment]
Hi,

**What is json2csv in above code?**
I don't understand this question...
`Transform` as imported from this library is the converter. It's a node Transform that receives json and produces csv.

**I have tried res.send(processor) to return the file.**
I don't now what that res is.
In nestjs you want to do something like:
```js
  import { createReadStream, createWriteStream } from 'fs';
  import { Transform } from '@json2csv/node';

  @Get()
  getFile(@Res() res: Response) {
    const input = createReadStream(inputPath, { encoding: 'utf8' });
    const parser = new Transform();
    
    input.pipe(parser).pipe(res);
  }
```

**I checked outputPath there is no csv file saved on that path.**
If you are piping to a writable file and your input was valid it should work.
If you want me to help you more, I need a sample project where I can replicate the problem.

**Is there a codesandbox or any working demo?**
That code that you just posted works.
You can see all the tests in this repository to see working examples.
